[DEFAULT]

logdir=/var/log/nova
state_path=/var/lib/nova
lock_path=/var/lock/nova
force_dhcp_release=True
iscsi_helper=tgtadm
libvirt_use_virtio_for_bridges=True
connection_type=libvirt
root_helper=sudo nova-rootwrap /etc/nova/rootwrap.conf
verbose=True
debug = True
use_syslog = True
syslog_log_facility = LOG_LOCAL0
rpc_backend = nova.rpc.impl_kombu
rabbit_host = {{ keystone_internal_ip }}

# FIXME: bad password/login
rabbit_password = guest
rabbit_userid = guest

my_ip = {{ ansible_eth2.ipv4.address }}
vncserver_listen = 0.0.0.0
# FIXME: eth1? seems to be removing eth2 ip...
vncserver_proxyclient_address = {{ ansible_eth2.ipv4.address }}
novncproxy_base_url = https://{{ keystone_external_ip }}:10003/vnc_auto.html
glance_host = {{ keystone_internal_ip }}
auth_strategy=keystone

# FIXME: not sure? was getting an error without it...
dhcpbridge = /usr/bin/nova-dhcpbridge
dhcpbridge_flagfile=/etc/nova/nova.conf
# END FIXME

#
# Network
#

network_api_class = nova.network.api.API
security_group_api = nova
firewall_driver = nova.virt.libvirt.firewall.IptablesFirewallDriver
network_manager = nova.network.manager.FlatDHCPManager
network_size = 254
allow_same_net_traffic = False
multi_host = True
send_arp_for_ha = True
share_dhcp_address = True
force_dhcp_release = True
flat_network_bridge = br100
# FIXME: correct interfaces?
flat_interface = {{ flat_interface }}
public_interface = {{ public_interface }}

vif_plugging_is_fatal: false
vif_plugging_timeout: 0

[database]
connection = mysql://nova:{{ nova_mysql_password}}@{{ keystone_internal_ip }}/nova

[keystone_authtoken]
auth_uri = http://{{ keystone_internal_ip }}:5000
auth_host = {{ keystone_internal_ip }}
auth_port = 35357
auth_protocol = https
admin_tenant_name = service
admin_user = {{ nova_admin_user }}
admin_password = {{ nova_admin_user_password }}
